### ISSUE TITLE
[u-boot][sdcard][ubuntu] latest odroid c2  patch not booting

### ISSUE THREAD

**Issue by redafenj** [xypron/u-boot-odroid-c2#2]
Hello,

I currently fetch master branch of uboot from denx. 

commit a63d800196ebee59b0f8ff924f67843cd597a8c1
Prepare v2017.05-rc3

Previous commit is odroid C2 MMC support.
I rebuilt uboot with odroid-c2_defconfig
I updated my sd card with the new images as explained in board/amlogic/odroid-c2/README
But when the new uboot is running I am getting a sd card error : 

U-Boot 2017.05-rc3 (May 03 2017 - 14:56:41 +0200) odroid-c2

DRAM:  2 GiB
MMC:   mmc@72000: 0, mmc@74000: 1
Using default environment

In:    serial@4c0
Out:   serial@4c0
Err:   serial@4c0
Net:   eth0: ethernet@c9410000
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Card did not respond to voltage select!
mmc_init: -95, time 10
MMC Device 1 not found
no mmc device at slot 1
MMC Device 2 not found
no mmc device at slot 2
ethernet@c9410000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
Could not initialize PHY ethernet@c9410000
ethernet@c9410000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
Could not initialize PHY ethernet@c9410000

Is it possible to know how I can know how to reproduce your test to make odroid C2 ubooting ?
 
PS: The rest of my sdcard is formatted as defined in hardkernel odroid C2 wiki with Ubuntu.
Note : With the hardkernel uboot my board is booting correctly without any issue.

**Comment by xypron** [comment]
@redafenj 

Could you, please, provide the output of 

    fdisk -l /dev/sdc

Replace /dev/sdc by the device representing your SD Card.

Which partition contains the boot.scr script?

Please provide the output of

    find .

for the directory with the boot script.

Best regards

Heinrich Schuchardt

**Comment by xypron** [comment]
I install the U-Boot as explained in the README.md of this project.
The Linux distro is Debian Stretch.
The kernel is from https://github.com/xypron/kernel-odroid-c2
Package flash-kernel package from http://git.xypron.de/?p=flash-kernel;a=summary creates boot.scr and copies the dtb to the boot partition.

**Comment by redafenj** [comment]
Hi xypron,

Thanks for you quick reply
I will set the same environment you are using and have a try. I will switch to Debian.

**Comment by redafenj** [comment]
Hi Xypron

I switch to a Debian Host, clone your uboot repo and follow the readme. Unfortunately I still have the same MMC voltage issue, which prevents uboot to find the sdcard content... 

Note : sd card is a SanDisk Ultra 16GB 
PS: The same sdcard with hardkernel uboot and ubuntu is working fine.

I will have a try with a different sd card or emmc. Am I the only one getting issue with this ? Do you want me to try to debug the mmc failure ?

**Comment by xypron** [comment]
@redafenj 

I have created project https://github.com/xypron/debian-image-odroid-c2 to create an SD card image.

You have to build on an arm64 system.

```
git clone https://github.com/xypron/debian-image-odroid-c2.git
cd debian-image-odroid-c2
make
sudo dd if=image of=TARGET bs=16M
```

Best regards

Heinrich
